Repository nasa-fornax/fornax-documentation, pull requests merged in 2025-09, with the labels that each got.

#134 Add a note about notebooks being read-only
  documentation/notebook_tutorials.md
Labels: content, maintenance

#128 Update console screenshots
  _static/forsc_dashboard.png
  _static/forsc_jupyterlab.png
Labels: content, maintenance

#139 Cleanup JupyterLab page and expand Working with Markdown Notebooks section
  documentation/dashboard.md
  documentation/jupyterlab.md
  documentation/markdown_and_code_dev.md
Labels: content

#146 Adding label to notebook section
  documentation/notebook_tutorials.md
Labels: maintenance
