Repository nasa-fornax/fornax-documentation, pull requests merged in 2025-08, with the labels that each got.

#93 MAINT: cleanup config and add github edit links
  myst.yml
Labels: technical enhancement

#103 update links from smce -> sciencecloud
  documentation/fornax_community_forum.md
  documentation/intro_quick_start.md
Labels: maintenance

#121 Reorganize TOC structure
  _static/forsc_dashboard.png
  documentation/compute_environments.md
  documentation/dashboard.md
  documentation/intro_fornax_resources.md
  documentation/intro_forsc.md
  documentation/jupyterlab.md
  documentation/markdown_and_code_dev.md
  documentation/notebook_tutorials.md
  documentation/python_notebooks.md
  documentation/quick_start.md
  documentation/server_options.md
  documentation/troubleshooting.md
  index.md
  myst.yml
Labels: maintenance

#125 Document the Fornax menu (including Update Notebooks)
  documentation/jupyterlab.md
Labels: content

#126 Changed the description of the small compute capacity to reflect the …
  documentation/intro_forsc.md
Labels: maintenance
